/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import logica.GestorPedido;

/**
 *
 * @author Personal
 */
public class GUIMenu extends javax.swing.JFrame {
    FondoPanel fondo = new FondoPanel();
    GestorPedido gestor_pedido = new GestorPedido();
    /**
     * Creates new form GUIMenu
     */
    public GUIMenu() {
        initComponents();
        myInit();
        this.pnlImagen=new FondoPanel();
    }
    private void myInit(){
        this.setLocation(200, 150);
        this.setSize(800, 400);
        //this.setContentPane(rootPane);
        //this.setIconImage(icon);
        this.setTitle("Menu Restaurante Unicauca");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlImagen = new FondoPanel();
        pnlMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxArroz = new javax.swing.JComboBox<>();
        btnReserva = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbxJugo = new javax.swing.JComboBox<>();
        cbxSopa = new javax.swing.JComboBox<>();
        cbxPrincipio = new javax.swing.JComboBox<>();
        cbxExtra = new javax.swing.JComboBox<>();
        lblArroz = new javax.swing.JLabel();
        lblJugo = new javax.swing.JLabel();
        lblSopa = new javax.swing.JLabel();
        lblPrincipio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblExtra = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 204));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        pnlImagen.setPreferredSize(new java.awt.Dimension(505, 100));

        javax.swing.GroupLayout pnlImagenLayout = new javax.swing.GroupLayout(pnlImagen);
        pnlImagen.setLayout(pnlImagenLayout);
        pnlImagenLayout.setHorizontalGroup(
            pnlImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        pnlImagenLayout.setVerticalGroup(
            pnlImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        getContentPane().add(pnlImagen);

        pnlMenu.setBackground(new java.awt.Color(0, 51, 204));
        pnlMenu.setPreferredSize(new java.awt.Dimension(505, 250));
        pnlMenu.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel1.setText("Menu del dia:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        pnlMenu.add(jLabel1, gridBagConstraints);

        cbxArroz.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        pnlMenu.add(cbxArroz, gridBagConstraints);

        btnReserva.setText("Reservar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        pnlMenu.add(btnReserva, gridBagConstraints);

        jLabel3.setText("   ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        pnlMenu.add(jLabel3, gridBagConstraints);

        cbxJugo.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        pnlMenu.add(cbxJugo, gridBagConstraints);

        cbxSopa.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        pnlMenu.add(cbxSopa, gridBagConstraints);

        cbxPrincipio.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        pnlMenu.add(cbxPrincipio, gridBagConstraints);

        cbxExtra.setMinimumSize(new java.awt.Dimension(200, 30));
        cbxExtra.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        pnlMenu.add(cbxExtra, gridBagConstraints);

        lblArroz.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblArroz.setForeground(new java.awt.Color(255, 255, 255));
        lblArroz.setText("Arroz:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        pnlMenu.add(lblArroz, gridBagConstraints);

        lblJugo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblJugo.setForeground(new java.awt.Color(255, 255, 255));
        lblJugo.setText("Jugo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        pnlMenu.add(lblJugo, gridBagConstraints);

        lblSopa.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblSopa.setForeground(new java.awt.Color(255, 255, 255));
        lblSopa.setText("Sopa:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        pnlMenu.add(lblSopa, gridBagConstraints);

        lblPrincipio.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblPrincipio.setForeground(new java.awt.Color(255, 255, 255));
        lblPrincipio.setText("Principio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        pnlMenu.add(lblPrincipio, gridBagConstraints);

        jLabel2.setText("               ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        pnlMenu.add(jLabel2, gridBagConstraints);

        lblExtra.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblExtra.setForeground(new java.awt.Color(255, 255, 255));
        lblExtra.setText("Otros:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        pnlMenu.add(lblExtra, gridBagConstraints);

        lblUsuario.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 10)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("El usuario ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pnlMenu.add(lblUsuario, gridBagConstraints);

        getContentPane().add(pnlMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMenu().setVisible(true);
            }
        });
    }
    public JButton getReservar(){
        return this.btnReserva;
    }
    public javax.swing.JComboBox<String> getArroz(){
        return this.cbxArroz;
    }
    public javax.swing.JComboBox<String> getJugo(){
        return this.cbxJugo;
    }
    public javax.swing.JComboBox<String> getSopa(){
        return this.cbxSopa;
    }
    public javax.swing.JComboBox<String> getPrincipio(){
        return this.cbxPrincipio;
    }
    public javax.swing.JComboBox<String> getOtros(){
        return this.cbxExtra;
    }
    public void setMenu(ArrayList<String> Menu){
        String[] arroz = Menu.get(0).split(",");
        for (int i = 0; i < arroz.length; i++) {
            this.cbxArroz.addItem(arroz[i]);
        }
        String[] jugo = Menu.get(1).split(",");
        for (int i = 0; i < jugo.length; i++) {
            this.cbxJugo.addItem(jugo[i]);
        }
        String[] sopa = Menu.get(2).split(",");
        for (int i = 0; i < sopa.length; i++) {
            this.cbxSopa.addItem(sopa[i]);
        }
        String[] principio = Menu.get(3).split(",");
        for (int i = 0; i < principio.length; i++) {
            this.cbxPrincipio.addItem(principio[i]);
        }
        String[] otros = Menu.get(4).split(",");
        for (int i = 0; i < otros.length; i++) {
            this.cbxExtra.addItem(otros[i]);
        }
    }
    public void setTiquetera(String tiquetera){
        this.lblUsuario.setText("El usuario "+tiquetera);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReserva;
    private javax.swing.JComboBox<String> cbxArroz;
    private javax.swing.JComboBox<String> cbxExtra;
    private javax.swing.JComboBox<String> cbxJugo;
    private javax.swing.JComboBox<String> cbxPrincipio;
    private javax.swing.JComboBox<String> cbxSopa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblArroz;
    private javax.swing.JLabel lblExtra;
    private javax.swing.JLabel lblJugo;
    private javax.swing.JLabel lblPrincipio;
    private javax.swing.JLabel lblSopa;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlImagen;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}

class FondoPanel extends JPanel{
    private Image imagen;
    @Override
    public void paint(Graphics g){
        imagen = new ImageIcon(getClass().getResource("/imagenes/unicauca.png")).getImage();
        g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
        setOpaque(false);
        super.paint(g);
    }
}
